### ISSUE TITLE
Заменить аватар Ани

### ISSUE THREAD

**Issue by pavelshadrin** [kuznetsov0209/stops63-web#2]
![img_1136](https://cloud.githubusercontent.com/assets/10427842/10433761/ab168414-7125-11e5-8ffc-b73e7fa38afc.JPG)

**Comment by eugenedemyan** [comment]
Нарезка новой аватарки: https://drive.google.com/open?id=0ByuhQcWXVsW8a0pmLWt4akpnTW8

**Comment by kuznetsov0209** [comment]
Готово
