### ISSUE TITLE
Добавить отзыв Антона

### ISSUE THREAD

**Issue by pavelshadrin** [kuznetsov0209/stops63-web#3]
«Красиво, выверенно, точно. Быстро находит остановки, показывает весь доступный транспорт, удобно пользоваться на ходу.
Антон Хмелёв, нефтяник»

![img_9436](https://cloud.githubusercontent.com/assets/10427842/10433778/cfda8354-7125-11e5-841a-98168e403d3b.JPG)
![img_3970](https://cloud.githubusercontent.com/assets/10427842/10433779/cfdaae2e-7125-11e5-9961-fedbdf6b6e99.jpeg)

**Comment by eugenedemyan** [comment]
Нарезка: https://drive.google.com/open?id=0ByuhQcWXVsW8a0pmLWt4akpnTW8

**Comment by kuznetsov0209** [comment]
Добавил
