### ISSUE TITLE
В форме фидбека остаётся одна строка

### ISSUE THREAD

**Issue by pavelshadrin** [kuznetsov0209/stops63-web#7]
<img width="423" alt="screen shot 2015-10-12 at 21 20 48" src="https://cloud.githubusercontent.com/assets/10427842/10433939/277afc00-7127-11e5-9b82-0d7911908e68.png">
Поставить курсор в начало, ввести три буквы, стереть три буквы — остаётся одна строка. Safari 9.0. В Хроме ок.

**Comment by kuznetsov0209** [comment]
won't fix
