### ISSUE TITLE
Обрезается звёздочка

### ISSUE THREAD

**Issue by pavelshadrin** [kuznetsov0209/stops63-web#8]
<img width="349" alt="screen shot 2015-10-12 at 21 22 14" src="https://cloud.githubusercontent.com/assets/10427842/10433969/560fa46c-7127-11e5-9612-4250de235d73.png">

**Comment by pavelshadrin** [comment]
В Сафари вроде только.

**Comment by kuznetsov0209** [comment]
Битая картинка была. Поправил
