### ISSUE TITLE
Впилить фактоид про 300 самарцев на место :-)

### ISSUE THREAD

**Issue by pavelshadrin** [kuznetsov0209/stops63-web#9]

**Comment by eugenedemyan** [comment]
Зачем? Ей же и сейчас пользуются, дай статистику лучше)

**Comment by kuznetsov0209** [comment]
Упс, уже выпилил. Возвращать?

**Comment by kuznetsov0209** [comment]
Паша, скинь стату

**Comment by pavelshadrin** [comment]
Давай напишем пока так:
«2811 самарцев воспользовались ...»

Айтюнз показывает примерно 4200 сессий в день, но это далеко не все юзеры. Сессий явно больше, чем пользователей. Смысл в том, чтобы через пару дней залить реальные данные, но чтобы они были примерно такой же величины.

**Comment by kuznetsov0209** [comment]
Впилил
